### ISSUE TITLE
Widget is not working under IOS

### ISSUE THREAD

**Issue by Andreas9030** [ioBroker/ioBroker.vis-history#8]
Hi,
is it planed to make it work under Safari in iOS?
Thank you

**Comment by Apollon77** [comment]
What exactly is the issue? Please be more specific

**Comment by Andreas9030** [comment]
Hi,
i build a View called in the ioBroker APP on my iPhone.
Here i want to display datas of the History Adapter.
In my Safari Browser on my Mac i can se the Values i am expecting.
But on my iPhone even the List doesn't appear.
![IMG_5015](https://user-images.githubusercontent.com/76253330/106360764-b1e7f380-631a-11eb-856f-90e19db14339.jpeg)
![IMG_5012](https://user-images.githubusercontent.com/76253330/106360766-b3b1b700-631a-11eb-8021-9d6b653ae095.jpeg)
![IMG_5014](https://user-images.githubusercontent.com/76253330/106360770-b9a79800-631a-11eb-8c97-8fe32d337321.PNG)

Thank You!!

**Comment by Andreas9030** [comment]
SORRY!!!
I refreshed my VIS-Editor and now it works perfekt!!!
Sorry!
